### ISSUE TITLE
TextureView doesn't support displaying a background drawable

### ISSUE THREAD

**Issue by JSONValidator** [sprylab/texturevideoview#17]
Hello
On Nexus 5X (Android 7.1.1)
```
Fatal Exception: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class com.sprylab.android.widget.TextureVideoView

Caused by android.view.InflateException: Binary XML file line #20: Error inflating class com.sprylab.android.widget.TextureVideoView

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at ru.artnp.ar.adapters.SliderAdapter.instantiateItem(SliderAdapter.java:53)
       at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1248)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
       at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:618)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
       at android.view.TextureView.setBackgroundDrawable(TextureView.java:316)
       at android.view.View.setBackground(View.java:18247)
       at android.view.View.<init>(View.java:4600)
       at android.view.View.<init>(View.java:4109)
       at android.view.TextureView.<init>(TextureView.java:159)
       at com.sprylab.android.widget.TextureVideoView.<init>(TextureVideoView.java:120)
       at com.sprylab.android.widget.TextureVideoView.<init>(TextureVideoView.java:116)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at ru.artnp.ar.adapters.SliderAdapter.instantiateItem(SliderAdapter.java:53)
       at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1248)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
       at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:618)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
How can I fix this?
Thank you

**Comment by JSONValidator** [comment]
With Samsung Galaxy Note2 (android 4.4.2) everything is ok

**Comment by hameno** [comment]
You need to check your layout XML and remove any background on the TextureVideoView as that is not supported (UnsupportedOperationException: TextureView doesn't support displaying a background drawable)

**Comment by JSONValidator** [comment]
Layout xml is ok, because on galaxy note2 it works
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#ffffffff">

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/imageView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="center"/>

    <ImageView
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:layout_centerInParent="true"
        android:src="@drawable/play"/>

    <com.sprylab.android.widget.TextureVideoView
        android:id="@+id/videoView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="gone"
        android:layout_alignParentBottom="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentTop="true" />

</RelativeLayout>

I think this problem is only for nexus, but not sure

**Comment by hameno** [comment]
Please check that you use the latest version of the library. Your stack trace line numbers don't match the latest code.
Also: don't compare different Android versions. It seems that Google added that check to newer android versions to prevent any wrong usage of TextureView as you can see the exception is in the framework code.

**Comment by rzimmer** [comment]
No feedback anymore, closing...
