### ISSUE TITLE
mSurface.release() never called?

### ISSUE THREAD

**Issue by godiecl** [sprylab/texturevideoview#3]
Hi rzimmer,

I'm using your very good library to show a video in my university internal aplication. It's work ok, but when i activate the StrictMode, Android show me the warning:

StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

I'm think is because the mSurface.release() method is never called.

**May be** the fix is in the file TextureVideoView.java
https://github.com/sprylab/texturevideoview/blob/master/library/src/main/java/com/sprylab/android/widget/TextureVideoView.java#L550  before to make mSurface null, call mSurface.release().

**Comment by rzimmer** [comment]
Hey mikaci, thanks for your feedback! You might be right with this. Do you have a complete stacktrace given from the strict mode? Unfortunately, currently I've not the time to investigate this issue myself, so I leave this open for later... You are, of course, welcome to try it out yourself and giving me feedback!

**Comment by godiecl** [comment]
Hi, thanks for the response.

I added the call to mSurface.release() in line 550 and the StrictMode was quickly silenced :dancers: 

This is the stacktrace:

```
E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'release' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at android.view.Surface.setNativeObjectLocked(Surface.java:471)
            at android.view.Surface.<init>(Surface.java:146)
            at com.sprylab.android.widget.TextureVideoView$7.onSurfaceTextureAvailable(TextureVideoView.java:543)
            at android.view.TextureView.getHardwareLayer(TextureView.java:370)
            at android.view.View.updateDisplayListIfDirty(View.java:14152)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.View.draw(View.java:14967)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
            at android.view.View.updateDisplayListIfDirty(View.java:14170)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.View.draw(View.java:14967)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
            at android.view.View.updateDisplayListIfDirty(View.java:14170)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.View.draw(View.java:14967)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
            at android.view.View.draw(View.java:15242)
            at android.widget.FrameLayout.draw(FrameLayout.java:598)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2906)
            at android.view.View.updateDisplayListIfDirty(View.java:14175)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2536)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by rzimmer** [comment]
Great, thanks for your quick feedback! I just pushed a corresponding commit and will hopefully soon find the time to release a new version to Maven central.
